### ISSUE TITLE
Duplicate credentialsrequests

### ISSUE THREAD

**Issue by mjudeikis** [openshift/cluster-ingress-operator#252] opened 2019-06-17 13:37 UTC
```
[mjudeiki@redhat openshift-azure]$ oc get credentialsrequests.cloudcredential.openshift.io 
NAME                               AGE
azure-openshift-ingress            179m
cloud-credential-operator-iam-ro   3h
openshift-image-registry           3h
openshift-ingress                  3h
```

We have 2 Ingress credentials evaluated from https://github.com/openshift/cluster-ingress-operator/blob/master/manifests/00-ingress-credentials-request.yaml

There should be logic to evaluate one based on the platform.

**Comment by ironcladlou** [comment] 2019-06-20 01:04
Pretty sure that to solve this we would need to take back control of these resource types from the CVO and manage them within the operator.

**Comment by mjudeikis** [comment] 2019-06-20 07:49
following this https://github.com/openshift/cloud-credential-operator/issues/72 

I would say keeping them in the release is good. Auditable, and if needed we can swap it with manually provisioned credentials instead of cred-minter running in the cluster. We could do that if we chose to because all requests are in one place. 

If we move control back - we would need to track multiple components and each new component would make this effort even harder. 

I think we just need logic in CVO to deploy only required credential and not "fire all and forget". This can be done by reading installconfig platform section.

**Comment by ironcladlou** [comment] 2019-06-25 20:38
Looks like the consensus is that this is not a bug (https://github.com/openshift/cloud-credential-operator/issues/72#issuecomment-504394054). Going to go ahead and close this. Let's take any further discussion to https://github.com/openshift/cloud-credential-operator/issues/72.

/close

**Closed by ironcladlou** 2019-06-25 20:38 UTC
